[package]
authors = ["w3ird-tech"]
default-run = "plank"
description = "A lightweight, secure Bitcoin wallet for the Mutinynet signet network (TUI)."
edition = "2021"
license = "AGPL-3.0-or-later"
name = "plank"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
arboard = "3.4.0"
bdk_esplora = { version = "0.20.1", features = ["async", "tokio"] }
bdk_wallet = { version = "1.2.0", features = ["rusqlite"] }
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.27"
dirs = "5.0"
env_logger = "0.10"
humantime = "2.2.0"
log = "0.4"
rand = "0.9.1"
ratatui = "0.26"
tui-textarea = { version = "0.3.0", features = ["crossterm"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.45.0", features = ["fs", "macros", "rt-multi-thread"] }
tokio-util = "0.7.15"
toml = "0.8"
